name: Deploy News App

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via central script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 159.65.154.221
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            bash /var/www/deploy.sh "news-app" "/var/www/news-app/frontend"
